if (ESP32_PIBOT_CNC_PENDANT_V1)
    message(STATUS "${BoldCyan}Adding PiBot configuration specific:${ColourReset}")
    set(TFT_TARGET "ESP32_PIBOT_CNC_PENDANT_V1")
    message(STATUS "${Cyan}Using board-specific sdkconfig: ${White}${CMAKE_SOURCE_DIR}/boards/pibot_pendant_v1_0/sdkconfig${ColourReset}\n")
    set(SDKCONFIG "${CMAKE_SOURCE_DIR}/boards/pibot_pendant_v1_0/sdkconfig")    
    list(APPEND EXTRA_COMPONENT_DIRS "${CMAKE_SOURCE_DIR}/boards/pibot_pendant_v1_0/components")
    add_compile_options("-I${CMAKE_SOURCE_DIR}/boards/pibot_pendant_v1_0/components/bsp")
    set (RESOLUTION_SCREEN "res_320_240")
    # Additional TFT settings when using TFT
    if(TFT_UI_SERVICE)
        set (TFT_BRIGHTNESS_CONTROL "ON")
        message(STATUS "\n${Cyan}Set Brigtness control: ${White}On${ColourReset}\n")
    endif()
    set (HARDWARE_BUTTONS "ON")
    message(STATUS "\n${Cyan}Set hardware buttons: ${White}On${ColourReset}\n")
    set (HARDWARE_ENCODER "ON")
    message(STATUS "\n${Cyan}Set hardware encoder: ${White}On${ColourReset}\n") 
    set (HARDWARE_SWITCH "ON")
    message(STATUS "\n${Cyan}Set hardware switch: ${White}On${ColourReset}\n")
    set (HARDWARE_POTENTIOMETER "ON")
    message(STATUS "\n${Cyan}Set hardware potentiometer: ${White}On${ColourReset}\n")
    message(STATUS "\n${Cyan}Set Resolution: ${White}${RESOLUTION_SCREEN}${ColourReset}\n")
endif()
