# DO NOT EDIT THIS FILE

# Include color definitions
include(cmake/colors.cmake)

# ===========================================
# Helper Functions
# ===========================================

function(check_single_selection var_list error_message selected_item)
    set(selected_count 0)
    set(last_selected "")
    foreach(item ${${var_list}})
        if(${item})
            math(EXPR selected_count "${selected_count} + 1")
            set(last_selected ${item})
        endif()
    endforeach()

    if(selected_count EQUAL 0)
        message(FATAL_ERROR "\n${BoldRed}No ${error_message} selected. Please select one in CMakeLists.txt${ColourReset}\n")
    elseif(selected_count GREATER 1)
        message(STATUS "\n\n${BoldRed}Multiple ${error_message}s selected:${ColourReset}")
        foreach(item ${${var_list}})
            if(${item})
                message(STATUS "  ${BoldRed}${item}${ColourReset}")
            endif()
        endforeach()
        message(STATUS "\n")
        message(FATAL_ERROR "\n${BoldRed}Please select only one ${error_message} in CMakeLists.txt${ColourReset}\n")
    else()
        message(STATUS "${Green}Selected ${error_message}: ${last_selected}${ColourReset}\n")
        set(${selected_item} ${last_selected} PARENT_SCOPE)
    endif()
endfunction()

# ===========================================
# Firmware Target Check
# ===========================================

set (fw_target "")
check_single_selection(FIRMWARES_LIST "firmware target" fw_target)

# ===========================================
# Target Board Check
# ===========================================

if(NOT TFT_TARGET)
    message(FATAL_ERROR 
        "\n"
        "${BoldRed}No hardware target defined. Please define a target in CMakeLists.txt${ColourReset}"
        "\n"
        "Now cmake will exit\n")
endif()


# ===========================================
# Platform Check
# ===========================================
set (board_target "")
check_single_selection(PLATFORMS_LIST "platform" board_target)

