# DO NOT EDIT THIS FILE
# Edit or Add target files in cmake/targets directory
#global drivers
set(EXTRA_COMPONENT_DIRS ${CMAKE_SOURCE_DIR}/hardware/common/drivers)

# all targets
file(GLOB_RECURSE TARGET_FILES "${CMAKE_SOURCE_DIR}/boards/*/board_config.cmake")

# Include all target files
foreach(TARGET_FILE ${TARGET_FILES})
  include(${TARGET_FILE})
endforeach()
